# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod 'Google/SignIn'
pod 'DGActivityIndicatorView'


target 'Incubee' do

end

target 'IncubeeTests' do

end

target 'Incubee QA' do

    
end
